import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import AuthMenu from "@/components/auth-menu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="sticky top-0 z-40 backdrop-blur bg-[#0b1413e6] border-b border-white/10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <div className="h-7 w-7 rounded-lg bg-[var(--ibm-blue,#0f62fe)] grid place-items-center">
                <span className="text-[10px] font-extrabold text-slate-900">CF</span>
              </div>
              <span className="font-semibold tracking-tight">CollabFlow Health</span>
            </Link>
            <nav className="hidden md:flex items-center gap-6 text-sm text-slate-300">
              <Link href="/modules" className="hover:text-white">Modules</Link>
              <Link href="/doctor/dashboard" className="hover:text-white">Doctor</Link>
              <Link href="/doctor/patients" className="hover:text-white">Patients</Link>
              <Link href="/doctor/emergencies" className="hover:text-white">Emergencies</Link>
            </nav>
            <AuthMenu />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
